Repository selsa-inube/inubekit-stack, pull requests merged in 2024-03, with the labels that each got.

#4 Update latest foundations version, spacing tokens and interface
  package-lock.json
  package.json
  src/Stack/index.tsx
  src/Stack/props.ts
  src/Stack/stories/Stack.stories.tsx
  src/Stack/stories/stories.styles.ts
  src/Stack/styles.js
  vite.config.ts
Labels: major

#5 Publish new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#6 Adjust and export interfaces
  src/Stack/index.tsx
  src/Stack/props.ts
  src/index.ts
Labels: minor

#7 Update inubekit/stack to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#8 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
